@startuml network

Node <|-- Computer


interface Node {
    + String name
    + String ip
    + String mac
    + String os
    + String version
    + String cpu
    + String ram
    + String disk
    + String network
    + String user
    + String password
    + String description
}

class Computer {
    + String name
    + String ip
    + String mac
    + String os
    + String version
    + String cpu
    + String ram
    + String disk
    + String network
    + String user
    + String password
    + String description
}